### ISSUE TITLE
Users are not always the same uid/gid on state directory after rebuild

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#183]
After rebuilding a cluster both prometheus and grafana failed to start in monitoring.yml. Investigation showed state files were not all owned by relevant users, e.g.:

```shell
[root@dev-control rocky]# ls -l /var/lib/state/prometheus/queries.active 
-rw-r--r--. 1 982 977 20001 May  5 12:26 /var/lib/state/prometheus/queries.active
[root@dev-control rocky]# id prometheus
uid=989(prometheus) gid=985(prometheus) groups=985(prometheus)
```

Running:
```shell
sudo chown -R prometheus /var/lib/state/prometheus # then  monitoring.yml reran OK
sudo chown -R grafana /var/lib/state/grafana
```

allowed `monitoring.yml` to complete.

The cloudalchemy roles create the users, so they'd need patching to check for UID/GID or something.

**Comment by m-bull** [comment]
Does this means that images need a consistent UID/GID for each user? This would prevent instances of a new immutable image not being able to access files on a persistent storage created by an old immutable image with different UID->username mappings.

I guess you can probably rely on the playbook creating users with the same UID/GID if the tasks run in the same order, but if you add some new functionality that creates a user in the middle of the playbook, its going to claim the next incremental UID and throw off all of the UIDs after that one.

**Comment by sjpb** [comment]
Or the roles chmod things as required, but that feels bad.

**Comment by sjpb** [comment]
For info: I think the actual problem was changing from using a pre-built image to a generic-cloud image. Looks like prometheus user got changed from 982 on former to 989 on latter.

**Comment by sjpb** [comment]
Current users with openhpc-220526-1354.qcow2 (in PR), on `control` node:

/var/spool/slurm/ slurm (for slurmctld): 202
/var/lib/mysql/ mysql (for slurmdbd): 27
/var/lib/prometheus (missing - failed run - is this not included in built image?)
/var/lib/grafana/ grafana: 984
/var/lib/podman podman: 1001

**Comment by sjpb** [comment]
Precreating the service users with defined {u,g}ids in the appliance won't be enough - the `slurm_image_builder` would also have to do it (with the same info, obviously) as the package installs setup most of the users. That affects CI/CaaS cases which use those images, so we could just live with the fact that we need to make sure `slurm_image_builder` remains consistent, till we get rid of it?

**Comment by sjpb** [comment]
@m-bull to allow us to move forward on this (and hence finish #173) I suggest:
- I add precreated users/groups to the slurm appliance with defined uids/gids, matching the resulting ids from using the current `slurm_image_builder` image + a slurm appliance run)
- I *don't* try to handle this in the `slurm_image_builder`, and we just tolerate the fact that will need rejigging if we add packages there which add additional users.

The `slurm_image_builder` is hopefully going away anyway once we've got a proper CaaS image build pipeline, so I think this is pragmatic.
