### ISSUE TITLE
Typo in dashboards

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#30]
Slurm jobs dashboard has widget labeled `Dashbaord URL`

https://grafana.com/grafana/dashboards/13535/revisions

**Comment by sjpb** [comment]
OpenHPC slurm dashboard also has typo "Network Traffic (recieve)"

**Comment by sjpb** [comment]
@jovial can't see any way I can fix this really - would be useful to fix if we're publicising dashboards (e.g. blogpost!)

**Comment by sjpb** [comment]
@jovial bump!

**Comment by jovial** [comment]
I've uploaded them with my own account to grafana.org. Not sure if we can set up an organisation where we can all edit them? Otherwise we could the dashboards to this repository. We'd need to change the upload role to upload a local file. What do you reckon?

**Comment by sjpb** [comment]
I guess at least putting them in the repo also allows people to propose PRs for them. Seems like the easiest option to me.
