### ISSUE TITLE
Error cloning openhpc-demo repo

### ISSUE THREAD

**Issue by verdurin** [stackhpc/ansible-slurm-appliance#66]
Following the instructions I saw a permission denied error when cloning the `openhpc-demo` repo:
```
[centos@cluster-admin00 src]$ git clone  git@github.com:stackhpc/openhpc-demo.git
Cloning into 'openhpc-demo'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by markgoddard** [comment]
Repo name was changed, but looks like the README was not updated. Should be https://github.com/stackhpc/ansible-slurm-appliance

**Comment by jovial** [comment]
I think `git@github.com:stackhpc/openhpc-demo.git` should redirect to `git@github.com:stackhpc/ansible-slurm-appliance.git`, but your SSH key isn't authorised for this repository. Mark is correct, we should switch to https for the documentation. Thanks for reporting the issue.
