### ISSUE TITLE
Versions of docker images not easily configurable

### ISSUE THREAD

**Issue by jovial** [stackhpc/ansible-slurm-appliance#70]
For example: https://github.com/stackhpc/ansible-slurm-appliance/blob/main/ansible/roles/kibana/templates/kibana.service.j2#L12

But I think the same is true for other podman services. Would be nice to factor this out into a role variable.

**Comment by sjpb** [comment]
Will be done for `filebeat` and `opensearch` by  #197. These are only current docker images.
