### ISSUE TITLE
grafana_address incorrect for multiple grafana hosts

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#75]
Appliance doesn't work with multiple grafana endpoints.

https://github.com/stackhpc/ansible-slurm-appliance/blob/8e1e094245927a21a02b081dbaeb8ed7ab889725/environments/common/inventory/group_vars/all/defaults.yml#L14 (changed in [88f2c4e6126](https://github.com/stackhpc/nrel-slurm-app/commit/88f2c4e612609b6c44f539c4b3cdbc91e6e5817a#diff-5303bbd2e8bb9f352714b320f2d9fde5b67cbe5d898b1b341a63616cf7f0e5c7L16)) sets `grafana_address: "{{ hostvars[groups['grafana'].0].api_address }}"`.

This means that on the 2nd grafana node, the "wait for grafana to start (http/s)" task in the cloudalchemy role [here](https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/main.yml#L50) `wait_for`'s the 1st grafana node to be ready.

The role default for `grafana_address` is `0.0.0.0` which makes sense. However the appliance also uses `grafana_address` as an "external" address in prometheus scrape definition here: https://github.com/stackhpc/ansible-slurm-appliance/blob/8e1e094245927a21a02b081dbaeb8ed7ab889725/environments/common/inventory/group_vars/all/prometheus.yml#L25

I wonder if we should:
a. Require/document that group `grafana` contains only a single host (due to lack of synced db/dashboard changes with multiple hosts)
b. Leave "grafana_address" undefined in `environment/common` (so role uses it's own default) and instead set `grafana_api_address` or `grafana_external_address` to "{{ hostvars[groups['grafana'].0].api_address }}" and use this for prom scrape definition?

Alternatively, if we allow multiple grafana hosts the prom scrape should be updated to include all.

Should also check if a. and b. above also apply to `elasticsearch_address` and `prometheus_address` defined in the same place?

**Comment by sjpb** [comment]
@jovial thoughts on suggestion above please?

**Comment by jovial** [comment]
I'm thinking that we should only support a single instance of grafana for now and add documentation about only adding a single host to the grafana group.

**Comment by sjpb** [comment]
Do we need to fix the reuse of grafana_host for both internal and external still?

**Comment by jovial** [comment]
Yeah, I think you are right in saying that we want to differentiate between the listening address and the address used to access the service externally. The current setup works if you only want to access grafana via one interface instead of binding to all. We definitely want to be able to change these independently. I quite like the idea of `grafana_listten_address` and `grafana_external_address`. `grafana_address` the role default would then be set to grafana_listen_address.

**Comment by sjpb** [comment]
- Don't want to support multiple grafana hosts, its too confusing.
- #101 fixes internal/external addresses (and allows for proxying grafana through the login/open ondemand node, which helps with the first point).
