### ISSUE TITLE
Terraform in skeleton is wrong

### ISSUE THREAD

**Issue by sjpb** [stackhpc/ansible-slurm-appliance#86]
Not sure PR #19 was really ready to merge

https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/skeleton/%7B%7Bcookiecutter.environment%7D%7D/terraform/inventory.tpl

does not define `control`. There is a comment in the above PR that this might be ok with appropriate overrides.

However I think we're assuming the cookiecutter should give us "`everything` + terraform". Are we actually happy with that? I am TBH. If so, maybe we should use the TF from the `nrel-workshop` branch (which is significantly more flexible in terms of allowing for image changes, multiple types of compute nodes, and auto-creating partition groups based those compute node types). That creates a separate control/login node which is probably a better "production-ready" example.

**Comment by sjpb** [comment]
@jovial @brtknr @mkjpryor comments appreciated.

**Comment by jovial** [comment]
I'm in favour of the example enabling everything by default. Using the terraform you linked to seems like a good idea.

**Comment by sjpb** [comment]
Now outdated.
